### ISSUE TITLE
[WirtBot] Access device by name

### ISSUE THREAD

**Issue by grollum** [b-m-f/Wirt#24]
Hi there. I started playing with this project, like it a lot :) 
My use case is to setup a VPN with certain services (e.g. a Nextcloud) for a closed group of people/devices.  I understand that the "Server" aka the wirtbot is meant to be the broker to all devices configured, thus the Nextcloud would be added as device to this network to be then accessible by all other devices. Thus people need to know the IP of the nextcloud device in the wirtbot-managed network. Could we add a DNS functionality to the server running wirtbot where it tries resolve IPs of devices in the VPN by their names given in the dashboard? Device configs could then contain a DNS entry set to the wirtbot host. 
I am not experienced with RUST but would probably give it a try if you would accept a PR for this.
Thanks for feedback and keep up the good work.

**Comment by b-m-f** [comment]
Hi @grollum ,

Sounds like an amazing idea.
How would the DNS resolution work on the clients?
Might be that this should be added to the `wg-quick` tool? Or maybe another wrapper such as `wg-quick` needs to be written for this.
It could read the config and set the routes on the client depending on its OS.

The frontend would need no changes for now from what I see. Could just use `DEVICE_NAME.internal` for a start.

Or do you already have another plan?

Feel free to ask questions if sth is unclear and Ill be happy to check the PR.

**Comment by grollum** [comment]
I was more thinking in the direction of running a real DNS service like bind9 on the host wirtbot resides at. This bind9 should manage a zone like .my-people.local and resolve requests to DEVICE.my-people.local to the IPs configured by wirtui. Devices` wireguard configs should then have a line `DNS = WIRTBOT_IP`. As this zone config could be accomplished by managing a text file a first simple implementation could be to give the wirtbot a path to the zone file to manage and update it on any device update coming from wirtui. What do you think?

**Comment by b-m-f** [comment]
Since the secure communication from UI to the Bot is already established this way of updating sounds good to me.

Why reinvent the wheel here.
Using a proven DNS server seems like a good solution.

One thing to make sure:
- bind Server only on WireGuard interface

This way the DNS should be secured sufficiently and I don't see why DNS shouldn't be resolved inside the network

**Comment by b-m-f** [comment]
Let me know if you have any questions!
The UI can use the device names as the name for the DNS entry. Will make this simpler

**Comment by grollum** [comment]
thanks a lot for your feedback and input :+1:  
I made a quick test setup using dnsmasq. With such a config:
`
domain-needed
bogus-priv

domain=my-people.local
expand-hosts
local=/my-people.local/ 

listen-address=127.0.0.1 
listen-address=10.10.0.1
bind-interfaces
server=8.8.8.8
server=1.1.1.1
`
we could simple add each device, 1 per line, to the `/etc/hosts` file of the dnsmasq host like this:
`WIREGUARD_IP DEVICE_NAME`

Then, with a client wireguard config 
`
[INTERFACE]
....
DNS = WIRTBOT_IP
`
we are able to resolve DNS requests like DEVICE_NAME.my-people.local accordingly.
So this quite simple setup is able to achieve what we want with one drawback: We have to restart dnsmasq with every change to the /etc/hosts file. I don't feel completely bad about it as we could simply leverage your solution with the wireguard-restarter. Alternatively we could adopt something self-built with https://www.npmjs.com/package/modern-dnsd or https://github.com/Xe/x/tree/master/cmd/dnsd

**Comment by grollum** [comment]
Please let me know again what you think about it :)

**Comment by b-m-f** [comment]
I like the idea, but I have a question.

Why do we need 
```
server=8.8.8.8
server=1.1.1.1
```
?

From how I see your solution with `dnsmasq` it will resolve any internal ones but forward all others to Cloudflares and Googles DNS servers. 
What I would want to avoid is passing all DNS requests through the Cluster when they should only be resolved there in the case of hitting an internal hostname.

So my laptop resolving the IP for `duckduckgo.com` over the Ethernet interface should use my normal DNS, accessing **NEXTCLOUD.my-people.local** should use the DNS on the WirtBot.


Maybe it is possible to add `DNS = WIRTBOT_IP` and add the hostnames to `AllowedIPs`?
In this case can `dnsmasq` work without specifying target DNS servers? Or would we need something else.
There is also the possibility to do a small DNS endpoint in Rust. We would also have full control over reloading the DNS on change etc.
This could be a new binary, or simply a coroutine in the existing one.


The `wireguard-restarter.sh` works fine for now because the interface is up so quickly. But it should eventually be replaced with something more solid. I see hooking more behaviour on this functionality too be a bit fragile.


Would you be at all interested in taking on the task of writing the Rust DNS endpoint?
Otherwise I am fine with `dnsmasq` without any servers to forward to, and would add a new ticket to implement this in Rust at a later point.

**Comment by grollum** [comment]
Thanks again for the good questions :) 
I get your points but do not agree with everything. Let's dig into it and start with the client behavior when using wireguards DNS config setting. On my test machine (ubuntu 20.04) this adds a line to `/etc/resolv.conf` like this

```
nameserver 10.10.0.1 # WIRTBOT
nameserver 127.0.0.53 # whatever my local setup had before
```

(For now, let's assume any other OS behaves the same, surely needs testing)

Given the above, your desired behavior client-side to only resolve DNS for the wirt-managed network 
can be achieved simply by using a dnsmasq config like this (tested):

```
domain-needed
bogus-priv
no-resolv
domain=my-people.local
expand-hosts
local=/my-people.local/ 

listen-address=127.0.0.1 
listen-address=10.10.0.1
bind-interfaces
```

So, adding `no-resolv` and removing the `server` lines achieves what you requested. 

Anyway, this leads to an important point: A client cannot control wether the wirtbot host resolves a DNS query or not (unless they run a dnsmasq or sth similiar on their own locally). If the wirtbot host resolves, the client will use that resolved IP for further processing, wether they intended to or not. Coming from my use case of being a service provider to other people this is not a problem. In fact, I consider resolving all DNS for them as a desired behavior (especially when combined with routed clients as already scheduled in #22). 

Now coming to the reloading part. dnsmasq has slower upstart speed then wireguard, roughly 1s on my test machine, so it's much slower then wireguard. Fortunately, dnsmasq can react to SIGHUP which makes it reload certain files, including hosts files without interrupting the service itself. This script handles it (tested, it does in fact not interrupt concurrent queries):

```
while inotifywait -e close_write /etc/hosts; do killall -s SIGHUP dnsmasq; done
```

Given this, I don't think wirtbot itself should provide DNS capabilities. From my point of view this would break SOC and given #22 it would require much more effort to provide good DNS service to actual VPN users (though I understand this would be more about my specific use). And to anyway answer your last question, I do not feel confident on adding this in RUST I'm afraid.

Conclusion:
I would stick with the dnsmasq solution with an inotifywait sending SIGHUP on host changes and suggest the following approach:

**WirtBot** gets the path to a hosts file thruogh ENV. Every update rewrites the contents of this file with one line per device. Serverside this is accompanied with the dnsmasq/inotifywait setup outlined above. 
**WirtUI** gets a switch in the server section to indicate wether the server supports DNS resolution acting as feature flag that is recognized by the devices section to add a DNS config line to the device config.

Let me say that I appreciate this discussion a lot. It made me learn much already, thanks for that :)

**Comment by grollum** [comment]
Yes I will take care about documentation :)

Frankly speaking, you lost me with your first point. I understand the threat but not the solution. Only thing I can add is that fiddling with resolv.conf manually is very specific and will not even work for all linux devices out there, not to speak about any other OS. 

Besides that I started implementation now :)

**Comment by b-m-f** [comment]
Sorry for the long time to respond. 

The solution I was thinking about is to append instead of prepending the WirtBot server as a nameserver in `/etc/resolv.conf` :)
As I understand it this should do a lookup on the normal Nameserver first, and if nothing is found the WirtBot nameserver is used.


Here is an example with appending and prepending:

## Prepending
### Resolve `google.com`
Ask Wirt nameserver -> no response -> ask next in line

#### Attack
Ask Wirt nameserver -> respond with fake google server
Cant do much

### Resolve `nextcloud.internal`
Ask Wirt nameserve -> immediately resolved to internal IP

## Appending
### Resolve `google.com`
Ask normal namerserver -> immediately resolved

### Resolve `nextcloud.internal`
Ask normal namerserver -> no entry found -> ask Wirt nameserver

#### Attack
Ask normal nameserver -> responds with fake Wirt server -> fake Wirt server wont have the correct Public/Private Keypair so WireGuard won't establish the connection.
**Still 'safe'**


Hope this makes more sense. I am not sure how much of a risk this is, I guess if you own the server you'd wanna make sure this wont happen. But shielding the client from a misconfigured server by appending instead of prepending to `/etc/resolv.conf` seems preferable from my point of view.
But maybe I am missing something here?

**Comment by grollum** [comment]
thanks a lot for the details. I get it. Then again I don't think this is a feasable solution.
For a starter, this would have to be implemented individually for all device/OS combinations, not even all linux systems work with resolvconf. 
Also I'm not convinced that WirtBot should implement defensive measures against this threat client-side . Users in this scenario move trust to the respective WirtBot operator intentionally and DNS is amongst that. This is also typical as of today for all "classic" VPN providers out there. To actually execute that kind of attack an offender needs to gain that much access and privilege to the host running WirtBot and dnsmasq that I even consider this attack harmless compared to what is possible with this level of access. 
One minor mitigation that comes to mind server-side, though, would be to explicitely block outgoing DNS queries with a firewall to prevent the described dnsmasq setup to resolve requests by forwarding them to somewhere else. I'll try to check if this works well and might include it to the docs.

**Comment by grollum** [comment]
Implementation wise I have questions on how to proceed (took me a bit to get used to rust initially). Right now the WirtBot gets requests containing the already rendered config for the wireguard interface. Shall I implement the DNS feature that way that the WirtUI sends already rendered content for the WirtBot's hostfile as well or shall I send device information in json structure to leave the formatting to the WirtBot? Personally, I usually prefer to leave that kind of things to the server. But as is this project is already structured differently It would be more concise (and therefor preferred by me) to leave that task to the UI and send a rendered hosts file for the server to simply save. Please kindly comment on this :)

**Comment by b-m-f** [comment]
Hey @grollum,

Thanks again for the feedback, I see your point about the threat level. Adding docs about potential security risks should be the best solution!


Regarding the payload I believe a new endpoint that accepts a hostsfile is a good solution.

If warp or Rust gets annoying feel free to open a PR at any level of readiness and I will be happy to give it a try

**Comment by grollum** [comment]
Thanks :)
I'll implement a new endpoint then and send it a pre-rendered hosts file. I'll get along with rust/warp no worries ;) UI wise I'll trigger a post to the new endpoint along with the general server update

**Comment by b-m-f** [comment]
Hi @grollum ,

Hows this issue getting along?

**Comment by grollum** [comment]
Hey @b-m-f sorry for the radio silence, got quite distracted by personal issues. I'm almost done with the rust/warp part, just managed my first successful request and will open a PR so you can start having a look on this.

**Comment by b-m-f** [comment]
No worries! Take it at your own pace!
Ill try to review this week, but from a quick glimpse over the code it looked good :)

**Comment by b-m-f** [comment]
@grollum To keep you updated:

- I have merged your endpoint work into master.
- I will now implement sending the names, given in the Interface when they are updated to the server
- Then I will provide a new ansible script that sets up everything, including DNS, as I believe it provides amazing UX and should be the default

Thanks again for the good work and feel free to jump in with new ideas and code any time you like!

**Comment by b-m-f** [comment]
Given the flexibility of https://coredns.io I am opting for this tool as the DNS server

**Comment by b-m-f** [comment]
Alright @grollum. Everything is merged and Forwarding enabled. 

I am currently preparing a blog post where I will go into more detail. Ill link it here when its published to hopefully answer all your questions :) Thanks again for the help, it was nice to work against a functioning API.

**Comment by b-m-f** [comment]
done in https://github.com/b-m-f/Wirt/pull/39
